engines:
  tslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      keyword-spacing:
        enabled: false
ratings:
  paths:
  - src/pages/*
  - src/app/*
  - src/modals/*
  - src/models/*
  - src/pages/*
  - src/providers/*
exclude_paths:
  - config/*
  - doc/*
  - env/*
  - lib/*
  - node_modules/*
  - platforms/*
  - plugins/*
  - resources/*
  - test-config/*
  - typings/*
  - www/*
