var sessions = /*[
    {title:"Introduction to Ionic", id: 0, speaker:"CHRISTOPHE COENRAETS", time:"9:40am", room:"Ballroom A", description: "In this session, you'll learn how to build a native-like mobile application using the Ionic Framework, AngularJS, and Cordova."},
    {title:"AngularJS in 50 Minutes", id: 1, speaker:"LISA SMITH", time:"10:10am", room:"Ballroom B", description: "In this session, you'll learn everything you need to know to start building next-gen JavaScript applications using AngularJS."},
    {title:"Contributing to Apache Cordova", id: 2, speaker:"JOHN SMITH", time:"11:10am", room:"Ballroom A", description: "In this session, John will tell you all you need to know to start contributing to Apache Cordova and become an Open Source Rock Star."},
    {title:"Mobile Performance Techniques", id:3, speaker:"JESSICA WONG", time:"3:10Pm", room:"Ballroom B", description: "In this session, you will learn performance techniques to speed up your mobile application."},
    {title:"Building Modular Applications", id:4, speaker:"LAURA TAYLOR", time:"2:00pm", room:"Ballroom A", description: "Join Laura to learn different approaches to build modular JavaScript applications."}
];
  */
    
    [
      {
        id: 3,
        VehicleId: "965",
        "Name": "Drvr PU Van 1",
        "Latitude": "564.326914",
        "Longitude": "-1347.538008",
        "RouteId": "30000",
        "TripId": "0",
        "RunId": { "-xsi:nil": "true" },
        "Direction": "UND",
        "DirectionLong": "Undefined",
        "Heading": "0",
        "Deviation": "0",
        "OpStatus": "NONE",
        "CommStatus": "OOS",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2062-04-27T17:41:36",
        "DisplayStatus": "On Time",
        "BlockFareboxId": { "-xsi:nil": "true" }
      },
      {
        "VehicleId": "1813",
        "Name": "1813",
        "Latitude": "42.1185",
        "Longitude": "-72.627674",
        "RouteId": "10000",
        "TripId": "0",
        "RunId": "2002",
        "Heading": "182",
        "Deviation": "0",
        "OpStatus": "LOGGED IN",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:09:53",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 2,
        "VehicleId": "1663",
        "Name": "1663",
        "Latitude": "42.178511",
        "Longitude": "-72.63714",
        "RouteId": "10000",
        "TripId": "0",
        "RunId": "2001",
        "Heading": "266",
        "Deviation": "0",
        "OpStatus": "LOGGED IN",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:10:01",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 3,
        "VehicleId": "1659",
        "Name": "1659",
        "Latitude": "42.145164",
        "Longitude": "-72.549676",
        "RouteId": "10000",
        "TripId": "0",
        "RunId": "203",
        "Heading": "60",
        "Deviation": "0",
        "OpStatus": "LOGGED IN",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:09:41",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 4,
        "VehicleId": "1552",
        "Name": "1552",
        "Latitude": "42.104252",
        "Longitude": "-72.666731",
        "RouteId": "10000",
        "TripId": "0",
        "RunId": "1007",
        "Heading": "84",
        "Deviation": "0",
        "OpStatus": "LOGGED IN",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:10:26",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 5,
        "VehicleId": "87",
        "Name": "3204",
        "Latitude": "42.457737",
        "Longitude": "-72.581482",
        "RouteId": "20031",
        "TripId": "2211",
        "RunId": "315",
        "Direction": "S",
        "DirectionLong": "Southbound",
        "Destination": "South Amherst",
        "Heading": "344",
        "Deviation": "0",
        "OpStatus": "TRIP START",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Sugarloaf Estates",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:00",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 6,
        "VehicleId": "1008",
        "Name": "MA Plate 822",
        "Latitude": "42.108076",
        "Longitude": "-72.60089",
        "RouteId": "10000",
        "TripId": "0",
        "RunId": "3333",
        "Heading": "184",
        "Deviation": "0",
        "OpStatus": "LOGGED IN",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:14",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 7,
        "VehicleId": "84",
        "Name": "3227",
        "Latitude": "42.405833",
        "Longitude": "-72.53241",
        "RouteId": "20030",
        "TripId": "2215",
        "RunId": "302",
        "Direction": "S",
        "DirectionLong": "Southbound",
        "Destination": "Old Belchertown Road",
        "Heading": "6",
        "Deviation": "0",
        "OpStatus": "TRIP START",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Puffton Village 1",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:11",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 8,
        "VehicleId": "106",
        "Name": "3202",
        "Latitude": "42.326238",
        "Longitude": "-72.53211",
        "RouteId": "20039",
        "TripId": "2215",
        "RunId": "392",
        "Direction": "W",
        "DirectionLong": "Westbound",
        "Destination": "Smith College",
        "Heading": "350",
        "Deviation": "0",
        "OpStatus": "TRIP START",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Hampshire College",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:25",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        id: 9,
        "VehicleId": "502",
        "Name": "7902",
        "Latitude": "42.387146",
        "Longitude": "-72.52641",
        "RouteId": "30043",
        "TripId": "2200",
        "RunId": "4311",
        "Direction": "W",
        "DirectionLong": "West",
        "Destination": "Northampton via Hampshire Mall",
        "Heading": "224",
        "Deviation": "3",
        "OpStatus": "ONTIME",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Fearing Street (In)",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:12:29",
        "DisplayStatus": "Late",
        "BlockFareboxId": "0"
      },
      {
        id: 10,
        "VehicleId": "82",
        "Name": "3214",
        "Latitude": "42.353439",
        "Longitude": "-72.476324",
        "RouteId": "20030",
        "TripId": "2215",
        "RunId": "305",
        "Direction": "N",
        "DirectionLong": "Northbound",
        "Destination": "North Amherst",
        "Heading": "242",
        "Deviation": "0",
        "OpStatus": "TRIP START",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Old Belchertown Road",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:39",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      
      {
        "VehicleId": "91",
        "Name": "3211",
        "Latitude": "42.378133",
        "Longitude": "-72.51988",
        "RouteId": "20038",
        "TripId": "2140",
        "RunId": "381",
        "Direction": "N",
        "DirectionLong": "Northbound",
        "Destination": "UMass / Haigis Mall",
        "Heading": "354",
        "Deviation": "3",
        "OpStatus": "ONTIME",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Amherst Post Office",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:25",
        "DisplayStatus": "Late",
        "BlockFareboxId": "0"
      },
      {
        id: 12,
        "VehicleId": "101",
        "Name": "3305",
        "Latitude": "42.35164",
        "Longitude": "-72.525676",
        "RouteId": "20031",
        "TripId": "2208",
        "RunId": "313",
        "Direction": "N",
        "DirectionLong": "Northbound",
        "Destination": "Sunderland",
        "Heading": "80",
        "Deviation": "2",
        "OpStatus": "ONTIME",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "The Brook (In)",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:31",
        "DisplayStatus": "Late",
        "BlockFareboxId": "0"
      },
      {
        "VehicleId": "85",
        "Name": "3221",
        "Latitude": "42.256083",
        "Longitude": "-72.572233",
        "RouteId": "20038",
        "TripId": "2135",
        "RunId": "382",
        "Direction": "S",
        "DirectionLong": "Southbound",
        "Destination": "Mt. Holyoke via Hamp Col.",
        "Heading": "200",
        "Deviation": "1",
        "OpStatus": "ONTIME",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "MHC Museum",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:32",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        scoop: 9,
        "VehicleId": "402",
        "Name": "7802",
        "Latitude": "42.339922",
        "Longitude": "-72.606166",
        "RouteId": "30043",
        "TripId": "2200",
        "RunId": "4312",
        "Direction": "E",
        "DirectionLong": "East",
        "Destination": "Amherst College via UMass",
        "Heading": "74",
        "Deviation": "2",
        "OpStatus": "ONTIME",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Russell/Bay (Barn Shops)",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:11:33",
        "DisplayStatus": "Late",
        "BlockFareboxId": "0"
      },
      {
        "VehicleId": "1630",
        "Name": "1630",
        "Latitude": "42.130794",
        "Longitude": "-72.796874",
        "RouteId": "10000",
        "TripId": "0",
        "RunId": "1007",
        "Heading": "292",
        "Deviation": "0",
        "OpStatus": "LOGGED IN",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:12:03",
        "DisplayStatus": "On Time",
        "BlockFareboxId": "0"
      },
      {
        "VehicleId": "1835",
        "Name": "1835",
        "Latitude": "42.105253",
        "Longitude": "-72.597121",
        "RouteId": "10007",
        "TripId": "2210",
        "RunId": "705",
        "Direction": "E",
        "DirectionLong": "Eastbound",
        "Destination": "State/Boston Rd  Eastfield Mall",
        "Heading": "48",
        "Deviation": "2",
        "OpStatus": "ONTIME",
        "CommStatus": "GOOD",
        "GPSStatus": "2",
        "LastStop": "Springfield Bus Terminal",
        "OnBoard": { "-xsi:nil": "true" },
        "LastUpdated": "2015-12-18T22:12:35",
        "DisplayStatus": "Late",
        "BlockFareboxId": "0"
      }
    ];

exports.findAll = function (req, res, next) {
    res.send(sessions);
};

exports.findById = function (req, res, next) {
    var id = req.params.id;
    res.send(sessions[id]);
};